version: '3.8'

services:
  backend:
    build: ./backend
    container_name: spring-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${RDS_ENDPOINT}:3306/projectdb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      APP_CLIENT_URL: http://${ALB_DNS_NAME}
    ports:
      - "8085:8085"
    networks:
      - app-network
    volumes:
      - ./backend/src:/workspace/app/src
    restart: always

  frontend:
    build: ./frontend
    container_name: vue-frontend
    environment:
      - VUE_APP_API_URL=http://${ALB_DNS_NAME}/api
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
