version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-db}
    ports:
      - "3306:3306"
    networks:
      - app-network
    restart: always
    

  backend:
    build: ./backend
    container_name: spring-backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_NAME:-db}?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-root}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-root}
      APP_CLIENT_URL: http://frontend
    ports:
      - "8085:8085"
    networks:
      - app-network
    volumes:
      - ./backend/src:/workspace/app/src
    restart: always
    

  frontend:
    build: ./frontend
    container_name: vue-frontend
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - backend


networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local